name: Autograding

on: [push]

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile
        run: javac *.java


      - name: test1 (1 pt)
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test1
          command: |
            set -e
            java TempConverter < tests/1_input.txt > actual.txt
            if diff --strip-trailing-cr actual.txt tests/1_expected.txt; then
              echo "PASS"
            else
              exit 1
            fi
          timeout: 2
          max-score: 1


      - name: test2 (1 pt)
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test2
          command: |
            set -e
            java TempConverter < tests/2_input.txt > actual.txt
            if diff --strip-trailing-cr actual.txt tests/2_expected.txt; then
              echo "PASS"
            else
              exit 1
            fi
          timeout: 2
          max-score: 1


      - name: test3 (1 pt)
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test3
          command: |
            set -e
            java TempConverter < tests/3_input.txt > actual.txt
            if diff --strip-trailing-cr actual.txt tests/3_expected.txt; then
              echo "PASS"
            else
              exit 1
            fi
          timeout: 2
          max-score: 1


      - name: test4 (1 pt)
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test4
          command: |
            set -e
            java TempConverter < tests/4_input.txt > actual.txt
            if diff --strip-trailing-cr actual.txt tests/4_expected.txt; then
              echo "PASS"
            else
              exit 1
            fi
          timeout: 2
          max-score: 1


      - name: test5 (1 pt)
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test5
          command: |
            set -e
            java TempConverter < tests/5_input.txt > actual.txt
            if diff --strip-trailing-cr actual.txt tests/5_expected.txt; then
              echo "PASS"
            else
              exit 1
            fi
          timeout: 2
          max-score: 1


      - name: test6 (1 pt)
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test6
          command: |
            set -e
            java TempConverter < tests/6_input.txt > actual.txt
            if diff --strip-trailing-cr actual.txt tests/6_expected.txt; then
              echo "PASS"
            else
              exit 1
            fi
          timeout: 2
          max-score: 1
          
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        if: always()
        with:
          runners: "test1,test2,test3,test4,test5,test6"